"""Track planted triangle/square pattern changes along GED edit paths.

Every graph of the synthetic TRIANGLE_SQUARE dataset carries a pendant
pattern on its last nodes: class 0 a triangle on nodes {11, 12, 13}, class 1
a square on nodes {10, 11, 12, 13}. This module walks every edit path through
the intermediate graphs generated by gedpaths
(data/GEDGraphs/F2/<DATASET>_<STRATEGY>/processed/data.pt, one graph per
row_idx of the merged results table), tracks per step whether the source
pattern is still intact and whether the target pattern has been created, and
joins this information onto the merged results table
(results/all_results.csv).

The stored intermediate graphs are used as ground truth instead of replaying
the edit-paths text file because the text file mixes numberings: DELETE
operations reference source-graph node ids while INSERT operations reference
target-graph node ids, and the source->target node mapping is not exported.
All intermediate graphs of a path share the source graph's numbering, so the
edge changed at step k is recovered as the symmetric difference between the
stored graphs of steps k-1 and k (exactly one edge per step; verified).

A pattern counts as intact/complete only while the edges incident to its
nodes are exactly those of the corresponding endpoint graph (the pattern
cycle plus its original attachment edges): any inserted edge touching a
pattern node, a deleted pattern edge, or a deleted attachment edge breaks it.

The target pattern lives in the target graph's numbering; it is mapped into
the path's numbering via a graph isomorphism between the last stored graph of
the path and the target graph.
"""

from __future__ import annotations

import glob
import os
import sys
from pathlib import Path
from typing import Dict, FrozenSet, List, Sequence, Set, Tuple

import click
import networkx as nx
import polars as pl

if __package__ in (None, ""):
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from utils.enrich_all_results import (
    _as_python_list,
    _get_attr,
    _load_collated_dataset,
)


Edge = Tuple[int, int]

PATTERN_INFO_COLUMNS = [
    "op_on_source_pattern",
    "op_on_target_pattern",
    "source_pattern_intact",
    "target_pattern_complete",
    "destroys_source_pattern",
    "creates_target_pattern",
    "src_destroyed_step",
    "tgt_created_step",
    "same_class_path",
    "pattern_phase",
]

PHASE_LABELS = {
    (1, 1): "both_present",
    (1, 0): "source_only",
    (0, 1): "target_only",
    (0, 0): "none_present",
}


def _load_graph_edge_sets(data_pt_path: Path) -> Tuple[List[Set[Edge]], List[int], List[int]]:
    """Return (edge_sets, num_nodes, labels) for a collated PyG data.pt.

    edge_index in these files is locally indexed per graph (0..n-1), so the
    node-slice offset must NOT be subtracted from the edge endpoints.
    """
    data_obj, slices = _load_collated_dataset(data_pt_path)
    edge_index = _get_attr(data_obj, "edge_index")
    y = _get_attr(data_obj, "y")
    labels = _as_python_list(y) if y is not None else []
    edge_slices = _as_python_list(_get_attr(slices, "edge_index"))
    node_slices = _as_python_list(_get_attr(slices, "x"))

    src_all = _as_python_list(edge_index[0])
    dst_all = _as_python_list(edge_index[1])

    edge_sets: List[Set[Edge]] = []
    num_nodes: List[int] = []
    for idx in range(len(node_slices) - 1):
        edge_start, edge_end = edge_slices[idx], edge_slices[idx + 1]
        edges = {
            (min(u, v), max(u, v))
            for u, v in zip(src_all[edge_start:edge_end], dst_all[edge_start:edge_end])
            if u != v
        }
        edge_sets.append(edges)
        num_nodes.append(node_slices[idx + 1] - node_slices[idx])
    return edge_sets, num_nodes, labels


def planted_pattern_nodes(num_nodes: int, label: int) -> Tuple[int, ...]:
    """Pattern nodes are the last 3 (triangle, class 0) or 4 (square, class 1)."""
    cycle_len = 3 if label == 0 else 4
    return tuple(range(num_nodes - cycle_len, num_nodes))


def planted_pattern_edges(nodes: Sequence[int]) -> FrozenSet[Edge]:
    cycle = {
        (
            min(nodes[i], nodes[(i + 1) % len(nodes)]),
            max(nodes[i], nodes[(i + 1) % len(nodes)]),
        )
        for i in range(len(nodes))
    }
    return frozenset(cycle)


def _incident_edges(edges: Set[Edge], nodes: FrozenSet[int]) -> FrozenSet[Edge]:
    return frozenset(e for e in edges if e[0] in nodes or e[1] in nodes)


def _map_target_pattern(
    final_edges: Set[Edge],
    final_num_nodes: int,
    target_edges: Set[Edge],
    target_num_nodes: int,
    target_pattern_nodes: Sequence[int],
    source_id: int,
    target_id: int,
) -> FrozenSet[int]:
    """Map the target's planted pattern nodes into the path's numbering.

    Uses any isomorphism between the last stored graph of the path and the
    target graph; with automorphisms the mapped pattern is well-defined up to
    symmetry, which is sufficient for tracking.
    """
    final_graph = nx.Graph()
    final_graph.add_nodes_from(range(final_num_nodes))
    final_graph.add_edges_from(final_edges)
    target_graph = nx.Graph()
    target_graph.add_nodes_from(range(target_num_nodes))
    target_graph.add_edges_from(target_edges)

    matcher = nx.algorithms.isomorphism.GraphMatcher(final_graph, target_graph)
    if not matcher.is_isomorphic():
        raise ValueError(
            f"Final stored graph of path {source_id}->{target_id} is not "
            "isomorphic to the target graph; graph data inconsistent."
        )
    inverse = {t: f for f, t in matcher.mapping.items()}
    return frozenset(inverse[n] for n in target_pattern_nodes)


def track_path(
    step_graphs: List[Set[Edge]],
    step_ids: List[int],
    num_nodes: int,
    source_label: int,
    target_edges: Set[Edge],
    target_num_nodes: int,
    target_label: int,
    source_id: int,
    target_id: int,
) -> List[Dict[str, object]]:
    """Return one record per path step.

    step_graphs[i] is the stored intermediate graph at step_ids[i]
    (step_id -1 is the source state, the last step is the target state).
    """
    src_nodes = frozenset(planted_pattern_nodes(num_nodes, source_label))
    src_reference = _incident_edges(step_graphs[0], src_nodes)

    tgt_nodes = _map_target_pattern(
        step_graphs[-1],
        num_nodes,
        target_edges,
        target_num_nodes,
        planted_pattern_nodes(target_num_nodes, target_label),
        source_id,
        target_id,
    )
    tgt_reference = _incident_edges(step_graphs[-1], tgt_nodes)

    records: List[Dict[str, object]] = []
    intact_flags: List[int] = []
    complete_flags: List[int] = []

    for idx, (step_id, edges) in enumerate(zip(step_ids, step_graphs)):
        if idx == 0:
            op_on_source = op_on_target = 0
        else:
            changed = edges.symmetric_difference(step_graphs[idx - 1])
            if len(changed) != 1:
                raise ValueError(
                    f"Step {step_id} of path {source_id}->{target_id} changes "
                    f"{len(changed)} edges instead of exactly one: {sorted(changed)}"
                )
            (u, v), = changed
            op_on_source = int(u in src_nodes or v in src_nodes)
            op_on_target = int(u in tgt_nodes or v in tgt_nodes)

        intact = int(_incident_edges(edges, src_nodes) == src_reference)
        complete = int(_incident_edges(edges, tgt_nodes) == tgt_reference)
        intact_flags.append(intact)
        complete_flags.append(complete)
        records.append(
            {
                "source_id": source_id,
                "target_id": target_id,
                "step_id": step_id,
                "op_on_source_pattern": op_on_source,
                "op_on_target_pattern": op_on_target,
                "source_pattern_intact": intact,
                "target_pattern_complete": complete,
                "pattern_phase": PHASE_LABELS[(intact, complete)],
            }
        )

    if complete_flags[-1] != 1:
        raise ValueError(
            f"Target pattern not complete at end of path {source_id}->{target_id}."
        )

    src_destroyed_step = next(
        (s for s, intact in zip(step_ids, intact_flags) if intact == 0), None
    )
    # tgt_created_step: first step of the trailing run in which the target
    # pattern stays complete through the end of the path.
    created_idx = len(complete_flags) - 1
    while created_idx > 0 and complete_flags[created_idx - 1] == 1:
        created_idx -= 1
    tgt_created_step = step_ids[created_idx]

    same_class_path = int(source_label == target_label)
    for idx, record in enumerate(records):
        previous_intact = intact_flags[idx - 1] if idx > 0 else 1
        record["destroys_source_pattern"] = int(
            previous_intact == 1 and intact_flags[idx] == 0
        )
        record["creates_target_pattern"] = int(record["step_id"] == tgt_created_step)
        record["src_destroyed_step"] = src_destroyed_step
        record["tgt_created_step"] = tgt_created_step
        record["same_class_path"] = same_class_path
    return records


def _resolve_ged_data_pt(ged_root: Path, dataset: str, path_strategy: str) -> Path:
    pattern = str(
        ged_root.joinpath("*", f"{dataset}_{path_strategy}", "processed", "data.pt")
    )
    matches = sorted(glob.glob(pattern))
    if not matches:
        raise FileNotFoundError(
            f"Could not find processed/data.pt for ({dataset}, {path_strategy}) "
            f"under '{ged_root}'."
        )
    if len(matches) > 1:
        click.echo(
            f"Warning: multiple matches for ({dataset}, {path_strategy}); using '{matches[0]}'."
        )
    return Path(matches[0])


def _collect_path_keys(input_csv: Path, dataset: str) -> pl.DataFrame:
    """Unique (path_strategy, row_idx, source_id, target_id, step_id) keys."""
    return (
        pl.scan_csv(str(input_csv))
        .filter(pl.col("dataset") == dataset)
        .select(
            pl.col("path_strategy"),
            pl.col("row_idx").cast(pl.Int64),
            pl.col("source_id").cast(pl.Float64).cast(pl.Int64),
            pl.col("target_id").cast(pl.Float64).cast(pl.Int64),
            pl.col("step_id").cast(pl.Float64).cast(pl.Int64),
        )
        .unique()
        .collect()
    )


def compute_pattern_info(
    dataset: str,
    keys: pl.DataFrame,
    ged_root: Path,
    tu_data_pt: Path,
) -> pl.DataFrame:
    tu_edge_sets, tu_num_nodes, tu_labels = _load_graph_edge_sets(tu_data_pt)
    for graph_id, (edges, n_nodes, label) in enumerate(
        zip(tu_edge_sets, tu_num_nodes, tu_labels)
    ):
        pattern = planted_pattern_edges(planted_pattern_nodes(n_nodes, label))
        if not pattern <= edges:
            raise ValueError(
                f"Graph {graph_id} (label {label}) does not contain its planted pattern."
            )

    all_rows: List[Dict[str, object]] = []
    for (strategy,), strategy_keys in keys.group_by("path_strategy"):
        data_pt = _resolve_ged_data_pt(ged_root, dataset, strategy)
        click.echo(f"Loading stored path graphs for strategy '{strategy}' from '{data_pt}'.")
        ged_edge_sets, ged_num_nodes, _ = _load_graph_edge_sets(data_pt)

        n_paths = 0
        for (source_id, target_id), path_keys in strategy_keys.group_by(
            ["source_id", "target_id"]
        ):
            path_keys = path_keys.sort("step_id")
            step_ids = path_keys.get_column("step_id").to_list()
            row_indices = path_keys.get_column("row_idx").to_list()
            step_graphs = [ged_edge_sets[r] for r in row_indices]
            num_nodes = ged_num_nodes[row_indices[0]]

            if step_ids[0] != -1:
                raise ValueError(
                    f"Path {source_id}->{target_id} ({strategy}) has no source row."
                )
            if step_graphs[0] != tu_edge_sets[source_id]:
                raise ValueError(
                    f"Stored source graph of path {source_id}->{target_id} "
                    f"({strategy}) differs from TUDataset graph {source_id}."
                )

            records = track_path(
                step_graphs,
                step_ids,
                num_nodes,
                tu_labels[source_id],
                tu_edge_sets[target_id],
                tu_num_nodes[target_id],
                tu_labels[target_id],
                source_id,
                target_id,
            )
            for record, row_idx in zip(records, row_indices):
                record["dataset"] = dataset
                record["path_strategy"] = strategy
                record["row_idx"] = row_idx
            all_rows.extend(records)
            n_paths += 1
        click.echo(f"Tracked {n_paths} paths for strategy '{strategy}'.")

    return pl.DataFrame(all_rows).select(
        ["dataset", "path_strategy", "row_idx", "source_id", "target_id", "step_id"]
        + PATTERN_INFO_COLUMNS
    )


def join_onto_results(
    input_csv: Path, pattern_info: pl.DataFrame, output_csv: Path, dataset: str
) -> None:
    pattern_lazy = (
        pattern_info.lazy()
        .select(["dataset", "path_strategy", "row_idx"] + PATTERN_INFO_COLUMNS)
        .rename({"row_idx": "_row_idx_int"})
    )

    enriched = (
        pl.scan_csv(str(input_csv))
        .with_columns(pl.col("row_idx").cast(pl.Int64).alias("_row_idx_int"))
        .join(
            pattern_lazy,
            on=["dataset", "path_strategy", "_row_idx_int"],
            how="left",
        )
        .drop("_row_idx_int")
    )

    null_count = (
        enriched.filter(pl.col("dataset") == dataset)
        .select(pl.col("source_pattern_intact").is_null().sum())
        .collect()
        .item()
    )
    if null_count > 0:
        raise ValueError(
            f"Join left {null_count} rows without pattern info; key mismatch between "
            "the results table and the stored path graphs."
        )

    try:
        enriched.sink_csv(str(output_csv))
    except (AttributeError, pl.exceptions.InvalidOperationError):
        enriched.collect(streaming=True).write_csv(str(output_csv))


@click.command()
@click.option(
    "--input-csv",
    default="results/all_results.csv",
    show_default=True,
    type=click.Path(path_type=Path, exists=True, dir_okay=False),
    help="Path to the input all_results.csv file.",
)
@click.option(
    "--output-csv",
    default="results/all_results_pattern.csv",
    show_default=True,
    type=click.Path(path_type=Path, dir_okay=False),
    help="Path to the pattern-enriched output CSV file.",
)
@click.option(
    "--pattern-info-csv",
    default="results/pattern_info_TRIANGLE_SQUARE.csv",
    show_default=True,
    type=click.Path(path_type=Path, dir_okay=False),
    help="Path for the standalone per-step pattern info CSV.",
)
@click.option(
    "--ged-root",
    default="data/GEDGraphs",
    show_default=True,
    type=click.Path(path_type=Path, exists=True, file_okay=False),
    help="Root folder containing GED graph datasets (stored path graphs).",
)
@click.option(
    "--tu-root",
    default="data/TUDatasets",
    show_default=True,
    type=click.Path(path_type=Path, exists=True, file_okay=False),
    help="Root folder containing the original TUDataset graphs.",
)
@click.option(
    "--dataset",
    default="TRIANGLE_SQUARE",
    show_default=True,
    help="Dataset name to process.",
)
@click.option(
    "--overwrite",
    is_flag=True,
    default=False,
    help="Allow overwriting existing output files.",
)
def main(
    input_csv: Path,
    output_csv: Path,
    pattern_info_csv: Path,
    ged_root: Path,
    tu_root: Path,
    dataset: str,
    overwrite: bool,
) -> None:
    for path in (output_csv, pattern_info_csv):
        if path.exists() and not overwrite:
            raise FileExistsError(
                f"Output file '{path}' already exists. Use --overwrite to replace it."
            )
        if path.parent and not path.parent.exists():
            os.makedirs(path.parent, exist_ok=True)

    keys = _collect_path_keys(input_csv, dataset)
    if keys.height == 0:
        raise ValueError(f"No rows for dataset '{dataset}' found in '{input_csv}'.")
    strategies = keys.get_column("path_strategy").unique().sort().to_list()
    click.echo(f"Found path strategies for {dataset}: {strategies}")

    tu_data_pt = tu_root.joinpath(dataset, "processed", "data.pt")
    pattern_info = compute_pattern_info(dataset, keys, ged_root, tu_data_pt)
    pattern_info.write_csv(str(pattern_info_csv))
    click.echo(
        f"Pattern info written to '{pattern_info_csv}' ({pattern_info.height} rows)."
    )

    join_onto_results(input_csv, pattern_info, output_csv, dataset)
    click.echo(f"Pattern-enriched results written to '{output_csv}'.")


if __name__ == "__main__":
    main()
