datasets:
  - {
        # all the options are mandatory (paths should be relative to the PYTHONPATH path)
        name: "NCI1_i-E_d-IsoN", # dataset name
        source: "path",  # dataset source type
        task: "graph_classification", # task type
        paths: {
          data: "data/GEDGraphs/F2/", # path to the dataset (will be downloaded if not present)
          results: "results/GIN/", # path to save the results
          models: "configs/NCI1/models_GIN.yml", # path to the model configuration file
          hyperparameters: "configs/NCI1/parameters.yml", # path to the hyperparameters configuration file
          splits: "../SimpleGNN/repo/src/simplegnn/datasets/splits/tu_splits/NCI1_splits.json", # path to the data splits file (contains train/val/test splits)
        }
    }
  - {
    # all the options are mandatory (paths should be relative to the PYTHONPATH path)
    name: "NCI1_Rnd", # dataset name
    source: "path",  # dataset source type
    task: "graph_classification", # task type
    paths: {
      data: "data/GEDGraphs/F2/", # path to the dataset (will be downloaded if not present)
      results: "results/GIN/", # path to save the results
      models: "configs/NCI1/models_GIN.yml", # path to the model configuration file
      hyperparameters: "configs/NCI1/parameters.yml", # path to the hyperparameters configuration file
      splits: "../SimpleGNN/repo/src/simplegnn/datasets/splits/tu_splits/NCI1_splits.json", # path to the data splits file (contains train/val/test splits)
    }
  }
