# main configuration file for running a basic graph classification experiment using the GIN and GCN models on the IMDB-16 dataset from the path collection.
datasets:
  - {
        # all the options are mandatory (paths should be relative to the PYTHONPATH path)
        name: "IMDB-16", # dataset name
        source: "path",  # dataset source type
        task: "graph_classification", # task type
        paths: {
          data: "data/Extended/", # path to the dataset (will be downloaded if not present)
          results: "results/GIN/", # path to save the results
          models: "configs/IMDB-16/models_GIN.yml", # path to the model configuration file
          hyperparameters: "configs/IMDB-16/parameters.yml", # path to the hyperparameters configuration file
          splits: "splits/IMDB-16_splits.json", # path to the data splits file (contains train/val/test splits)
        }
    }
  - {
        # all the options are mandatory (paths should be relative to the PYTHONPATH path)
        name: "IMDB-16", # dataset name
        source: "path",  # dataset source type
        task: "graph_classification", # task type
        paths: {
          data: "data/Extended/", # path to the dataset (will be downloaded if not present)
          results: "results/GCN/", # path to save the results
          models: "configs/IMDB-16/models_GCN.yml", # path to the model configuration file
          hyperparameters: "configs/IMDB-16/parameters.yml", # path to the hyperparameters configuration file
          splits: "splits/IMDB-16_splits.json", # path to the data splits file (contains train/val/test splits)
        }
    }
  - {
    # all the options are mandatory (paths should be relative to the PYTHONPATH path)
    name: "IMDB-16", # dataset name
    source: "path",  # dataset source type
    task: "graph_classification", # task type
    paths: {
      data: "data/Extended/", # path to the dataset (will be downloaded if not present)
      results: "results/GAT/", # path to save the results
      models: "configs/IMDB-16/models_GAT.yml", # path to the model configuration file
      hyperparameters: "configs/IMDB-16/parameters.yml", # path to the hyperparameters configuration file
      splits: "splits/IMDB-16_splits.json", # path to the data splits file (contains train/val/test splits)
    }
  }
  - {
    # all the options are mandatory (paths should be relative to the PYTHONPATH path)
    name: "IMDB-16", # dataset name
    source: "path",  # dataset source type
    task: "graph_classification", # task type
    paths: {
      data: "data/Extended/", # path to the dataset (will be downloaded if not present)
      results: "results/GATv2/", # path to save the results
      models: "configs/IMDB-16/models_GATv2.yml", # path to the model configuration file
      hyperparameters: "configs/IMDB-16/parameters.yml", # path to the hyperparameters configuration file
      splits: "splits/IMDB-16_splits.json", # path to the data splits file (contains train/val/test splits)
    }
  }
  - {
    # all the options are mandatory (paths should be relative to the PYTHONPATH path)
    name: "IMDB-16", # dataset name
    source: "path",  # dataset source type
    task: "graph_classification", # task type
    paths: {
      data: "data/Extended/", # path to the dataset (will be downloaded if not present)
      results: "results/GraphSAGE/", # path to save the results
      models: "configs/IMDB-16/models_GraphSAGE.yml", # path to the model configuration file
      hyperparameters: "configs/IMDB-16/parameters.yml", # path to the hyperparameters configuration file
      splits: "splits/IMDB-16_splits.json", # path to the data splits file (contains train/val/test splits)
    }
  }

