models:
  - - { layer_type: linear,
        out_features: 64,
        bias: True,
        activation: torch.nn.LeakyReLU(),
  }
    - { layer_type: gat_convolution,
        bias: True,
        out_channels: 64,
        activation: torch.nn.LeakyReLU(),
        batch_norm: True,
        num_heads: 4,
        residual: False,
        dropout: 0.2,
    }
    - { layer_type: gat_convolution,
        bias: True,
        out_channels: 64,
        activation: torch.nn.LeakyReLU(),
        batch_norm: True,
        num_heads: 4,
        residual: False,
        dropout: 0.2,
    }
    - { layer_type: global_pooling,
        mode: mean,
    }
    - { layer_type: batch_norm,
    }
    - { layer_type: dropout,
        p: 0.2,
    }
    - { layer_type: linear,
        out_features: 64,
        bias: True,
        activation: torch.nn.LeakyReLU(),
    }
    - { layer_type: linear,
        out_features: 32,
        bias: True,
        activation: torch.nn.LeakyReLU(),
    }
    - { layer_type: linear,
        out_features: 3,
        bias: True,
    }